### ISSUE TITLE
Excuse me, if I have already got the engine file, can I not use the build process? What is the purpose of that build? There is no new model file output ah? In addition, if this is used for tracking, which piece of code needs to be modified?

### ISSUE THREAD

**Issue by orderer0001** [triple-Mu/YOLOv8-TensorRT#122]
Excuse me, if I have already got the engine file, can I not use the build process? What is the purpose of that build? There is no new model file output ah? In addition, if this is used for tracking, which piece of code needs to be modified?

**Comment by triple-Mu** [comment]
> 

This repo has pruned the yolov8 model and added the NMS plugin. So you should use `expory-det.py` to export onnx model and then build engine by `trtexec` or `build.py`(But it is not recommand to use python trt, because py trt is different from cpp trt).

The detection result is `x1y1x2y2` format. So you and add the bboxes into tracker and get track resuts to update.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
