### ISSUE TITLE
c++ Detection Batch Inference

### ISSUE THREAD

**Issue by galAcarteav** [triple-Mu/YOLOv8-TensorRT#17]
Hey, @triple-Mu
First of all, thanks for sharing your amazing repo!
There is any why you can explain how I run batch of 3 images?
can't find how to refactor the YOLOv8::copy_from_Mat function to copy the images right

**Comment by triple-Mu** [comment]
Sorry, currently I have not developed an interface for mini-batch inference.
Since batch inference needs to export a fixed batch model (>=1) or a dynamic batch model, the corresponding pre- and post-processing needs to be refactored. 
I will consider adding this feature in the next version. 
In addition, I don't know if you have any intention to pr？
Thank you for your attention!

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!

**Comment by Egorundel** [comment]
Have you added batch inference? @triple-Mu
