### ISSUE TITLE
Detect only one object or none will cause Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by MomoHsieh** [triple-Mu/YOLOv8-TensorRT#68]
If there is only one or none obj detected, the script will crash

Can you check with seg_postprocess in side if there is error?
 
I think there is mask count error

``` 
python3 infer-seg-without-torch.py --engine yolov8s-seg.engine --imgs data/zidane.jpg --show --method pycuda --conf-thres 0.9
[04/13/2023-18:19:36] [TRT] [W] Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
Segmentation fault (core dumped)
```

thanks

**Comment by triple-Mu** [comment]
> If there is only one or none obj detected, the script will crash
> 
> Can you check with seg_postprocess in side if there is error?
> 
> I think there is mask count error
> 
> ```
> python3 infer-seg-without-torch.py --engine yolov8s-seg.engine --imgs data/zidane.jpg --show --method pycuda --conf-thres 0.9
> [04/13/2023-18:19:36] [TRT] [W] Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
> Segmentation fault (core dumped)
> ```
> 
> thanks

Could locate which line core dumped?

**Comment by enemy1205** [comment]
Maybe i also met this problem ,
the details error info:
` what():  OpenCV(4.6.0) /home/xxx/xxx/opencv-4.6.0/modules/core/src/matrix_expressions.cpp:24: error: (-5:Bad argument) Matrix operand is an empty matrix. in function 'checkOperandsExist'`
And according to my debug:
core dumped maybe in `yolov8-seg.hpp` 466 line
`objs[i].boxMask = mask(objs[i].rect) > 0.5f;`
it's because the rect is abnormal ,which leading to when cropping roi area incorrectly.  `mask(objs[i].rect)` here.
And in the same file , i find when  score_thres gives the default threshold of 0.25 ，many objects that fit the threshold ,will have a bounding box with very unusual value , like this:
![截图 2023-04-18 23-37-06](https://user-images.githubusercontent.com/30740917/232829781-a355ba8c-6d5b-4ab9-9b21-b756c26b66e3.png)
the x0 , y0 ,x1 ,y1 will be very small , and i think it lead the core dumped above.

**Comment by triple-Mu** [comment]
> Maybe i also met this problem ,
> 
> the details error info:
> 
> ` what():  OpenCV(4.6.0) /home/xxx/xxx/opencv-4.6.0/modules/core/src/matrix_expressions.cpp:24: error: (-5:Bad argument) Matrix operand is an empty matrix. in function 'checkOperandsExist'`
> 
> And according to my debug:
> 
> core dumped maybe in `yolov8-seg.hpp` 466 line
> 
> `objs[i].boxMask = mask(objs[i].rect) > 0.5f;`
> 
> it's because the rect is abnormal ,which leading to when cropping roi area incorrectly.  `mask(objs[i].rect)` here.
> 
> And in the same file , i find when  score_thres gives the default threshold of 0.25 ，many objects that fit the threshold ,will have a bounding box with very unusual value , like this:
> 
> ![截图 2023-04-18 23-37-06](https://user-images.githubusercontent.com/30740917/232829781-a355ba8c-6d5b-4ab9-9b21-b756c26b66e3.png)
> 
> the x0 , y0 ,x1 ,y1 will be very small , and i think it lead the core dumped above.

Very good topic.
Maybe we should drop some small or   illegal boxes and then do segment postprocess.

Are you willing to pr for this？
Thanks so much!

**Comment by enemy1205** [comment]
Fine , i find that this is not small or illegal boxes which cause the core dumped
After debugging for a long time, the output format of the tensorRT variable may not be as implemented in the git repository code. I will submit a merge request as soon as possible with a material explanation.
The output of yolov8-seg is likely to be very different from the previous generation.

**Comment by triple-Mu** [comment]
closed, feel free to reopen it if you have further questions. Thanks!
